create table job_execution (
    id_job_execution int8 generated by default as identity,
    file_name varchar(100) not null,
    ind_status varchar(30) not null,
    started_at date not null,
    updated_at date not null,
    primary key (id_job_execution)
);

alter table facility_business_object
add column id_job_execution int8 not null;

alter table if exists facility_business_object
add constraint FKkl8ldmkg1oxe49osh61s2cb7j foreign key (id_job_execution) references job_execution;