name: Synopsys BlackDuck Security Scan

on:
  push:
    branches: [CDT]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [CDT]

jobs:
  security:
    name: Black Duck Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify --settings settings.xml

      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.0
        env:
          NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
        with:
          scan-mode: INTELLIGENT # RAPID
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.9.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
